# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: fixops-backend-service
  namespace: fixops
  labels:
    app: fixops-backend
spec:
  selector:
    app: fixops-backend
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: fixops-frontend-service
  namespace: fixops
  labels:
    app: fixops-frontend
spec:
  selector:
    app: fixops-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---
# External LoadBalancer (for bank access)
apiVersion: v1
kind: Service
metadata:
  name: fixops-external-lb
  namespace: fixops
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/cert-id"
spec:
  selector:
    app: fixops-backend
  ports:
  - name: https
    port: 443
    targetPort: 8001
    protocol: TCP
  type: LoadBalancer