apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fixops-azure-deployment
  title: Deploy FixOps to Azure AKS
  description: |
    Deploy FixOps Decision Engine to Azure AKS cluster using Terraform.
    Provisions AKS resources, Azure Disk storage, Application Gateway ingress, and monitoring.
  annotations:
    backstage.io/managed-by-location: url:https://github.com/DevOpsMadDog/Fixops/tree/main/deployment-packs/azure
  tags:
    - azure
    - aks
    - terraform
    - security
    - devsecops
    - fixops
spec:
  owner: platform-engineering
  type: infrastructure
  
  parameters:
    - title: Azure Configuration
      required:
        - deployment_name
        - environment
        - location
        - resource_group_name
        - cluster_name
      properties:
        deployment_name:
          title: Deployment Name
          type: string
          description: Unique name for this FixOps deployment
          default: fixops-decision-engine
          pattern: '^[a-z0-9-]+$'
        environment:
          title: Environment
          type: string
          description: Target deployment environment
          enum:
            - development
            - staging
            - production
          enumNames:
            - Development
            - Staging
            - Production
        location:
          title: Azure Location
          type: string
          description: Azure region for deployment
          enum:
            - eastus
            - eastus2
            - westus
            - westus2
            - centralus
            - northeurope
            - westeurope
            - uksouth
            - southeastasia
            - japaneast
          default: eastus
        resource_group_name:
          title: Resource Group Name
          type: string
          description: Azure resource group for deployment
        cluster_name:
          title: AKS Cluster Name
          type: string
          description: Existing AKS cluster name
        domain_name:
          title: Domain Name
          type: string
          description: Domain name for FixOps (e.g., example.com)
          
    - title: FixOps Configuration
      required:
        - backend_replicas
        - storage_size
      properties:
        backend_replicas:
          title: Backend Replicas
          type: integer
          description: Number of backend replicas for high availability
          default: 3
          minimum: 1
          maximum: 10
        storage_size:
          title: Evidence Lake Storage
          type: string
          description: Persistent storage size for audit data
          default: 10Gi
          enum: [10Gi, 50Gi, 100Gi, 500Gi, 1Ti]
        enable_monitoring:
          title: Enable Azure Monitor
          type: boolean
          description: Enable Azure Monitor integration
          default: true
        enable_autoscaling:
          title: Enable Autoscaling
          type: boolean
          description: Enable horizontal pod autoscaling
          default: true
        
    - title: Terraform State
      required:
        - terraform_resource_group
        - terraform_storage_account
      properties:
        terraform_resource_group:
          title: Terraform State Resource Group
          type: string
          description: Resource group for Terraform state storage
        terraform_storage_account:
          title: Terraform State Storage Account
          type: string
          description: Storage account for Terraform state

  steps:
    - id: fetch-base
      name: Fetch FixOps Terraform Module
      action: fetch:template
      input:
        url: https://github.com/DevOpsMadDog/Fixops/tree/main/deployment-packs/azure/terraform
        targetPath: ./terraform
        values:
          deployment_name: ${{ parameters.deployment_name }}
          environment: ${{ parameters.environment }}
          location: ${{ parameters.location }}
          resource_group_name: ${{ parameters.resource_group_name }}
          cluster_name: ${{ parameters.cluster_name }}
          domain_name: ${{ parameters.domain_name }}
          backend_replicas: ${{ parameters.backend_replicas }}
          storage_size: ${{ parameters.storage_size }}
          enable_monitoring: ${{ parameters.enable_monitoring }}
          enable_autoscaling: ${{ parameters.enable_autoscaling }}
          terraform_resource_group: ${{ parameters.terraform_resource_group }}
          terraform_storage_account: ${{ parameters.terraform_storage_account }}

    - id: create-tfvars
      name: Generate terraform.tfvars
      action: roadiehq:utils:fs:write
      input:
        path: ./terraform/terraform.tfvars
        content: |
          deployment_name            = "${{ parameters.deployment_name }}"
          environment                = "${{ parameters.environment }}"
          location                   = "${{ parameters.location }}"
          resource_group_name        = "${{ parameters.resource_group_name }}"
          cluster_name               = "${{ parameters.cluster_name }}"
          domain_name                = "${{ parameters.domain_name }}"
          backend_replicas           = ${{ parameters.backend_replicas }}
          storage_size               = "${{ parameters.storage_size }}"
          enable_monitoring          = ${{ parameters.enable_monitoring }}
          enable_autoscaling         = ${{ parameters.enable_autoscaling }}
          terraform_resource_group   = "${{ parameters.terraform_resource_group }}"
          terraform_storage_account  = "${{ parameters.terraform_storage_account }}"
          
          tags = {
            "ManagedBy"   = "Backstage"
            "Owner"       = "platform-engineering"
            "Application" = "FixOps"
          }

    - id: create-deploy-script
      name: Create Deployment Script
      action: roadiehq:utils:fs:write
      input:
        path: ./deploy.sh
        content: |
          #!/bin/bash
          
          set -e
          
          echo "🚀 Deploying FixOps to Azure AKS"
          echo "================================="
          echo "Deployment: ${{ parameters.deployment_name }}"
          echo "Environment: ${{ parameters.environment }}"
          echo "Location: ${{ parameters.location }}"
          echo "Cluster: ${{ parameters.cluster_name }}"
          echo ""
          
          command -v terraform >/dev/null 2>&1 || { echo "❌ terraform not found"; exit 1; }
          command -v az >/dev/null 2>&1 || { echo "❌ azure cli not found"; exit 1; }
          command -v kubectl >/dev/null 2>&1 || { echo "❌ kubectl not found"; exit 1; }
          
          echo "🔐 Checking Azure authentication..."
          az account show >/dev/null 2>&1 || az login
          
          echo "🔧 Configuring kubectl for AKS cluster..."
          az aks get-credentials \
            --resource-group ${{ parameters.resource_group_name }} \
            --name ${{ parameters.cluster_name }} \
            --overwrite-existing
          
          cd terraform/
          
          # Initialize Terraform
          echo "🔧 Initializing Terraform..."
          terraform init
          
          echo "✅ Validating Terraform configuration..."
          terraform validate
          
          # Plan deployment
          echo "📋 Planning deployment..."
          terraform plan \
            -var="emergent_llm_key=$EMERGENT_LLM_KEY" \
            -out=fixops.plan
          
          # Apply deployment
          echo "🚀 Applying deployment..."
          terraform apply -auto-approve fixops.plan
          
          echo ""
          echo "✅ FixOps deployed successfully to Azure AKS!"
          echo ""
          echo "🌐 Access Information:"
          terraform output
          
          echo ""
          echo "🧪 Validation Commands:"
          echo "kubectl get pods -n $(terraform output -raw namespace)"
          echo "kubectl get svc -n $(terraform output -raw namespace)"
          echo "curl $(terraform output -raw fixops_api_url)/health"

    - id: create-destroy-script
      name: Create Destroy Script
      action: roadiehq:utils:fs:write
      input:
        path: ./destroy.sh
        content: |
          #!/bin/bash
          
          set -e
          
          echo "⚠️  Destroying FixOps deployment from Azure AKS"
          echo "==============================================="
          echo "Deployment: ${{ parameters.deployment_name }}"
          echo "Environment: ${{ parameters.environment }}"
          echo ""
          
          read -p "Are you sure you want to destroy this deployment? (yes/no): " confirm
          if [ "$confirm" != "yes" ]; then
            echo "❌ Destroy cancelled"
            exit 0
          fi
          
          cd terraform/
          
          echo "🗑️  Destroying infrastructure..."
          terraform destroy -auto-approve \
            -var="emergent_llm_key=$EMERGENT_LLM_KEY"
          
          echo "✅ FixOps deployment destroyed"

    - id: create-catalog-info
      name: Create Backstage Catalog Entry
      action: roadiehq:utils:fs:write
      input:
        path: ./catalog-info.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.deployment_name }}
            title: FixOps ${{ parameters.environment | title }} (Azure)
            description: FixOps Decision Engine deployed to Azure AKS via Backstage
            annotations:
              backstage.io/techdocs-ref: dir:.
              azure.com/aks-cluster: ${{ parameters.cluster_name }}
              azure.com/location: ${{ parameters.location }}
              azure.com/resource-group: ${{ parameters.resource_group_name }}
              fixops.io/api-url: https://fixops-${{ parameters.environment }}.${{ parameters.domain_name }}
              kubernetes.io/namespace: fixops
              terraform.io/state-storage: ${{ parameters.terraform_storage_account }}
            tags:
              - azure
              - aks
              - security
              - devsecops
              - ${{ parameters.environment }}
              - terraform-managed
            links:
              - url: https://fixops-${{ parameters.environment }}.${{ parameters.domain_name }}
                title: FixOps API
                icon: web
              - url: https://portal.azure.com/#@/resource/subscriptions/SUBSCRIPTION_ID/resourceGroups/${{ parameters.resource_group_name }}/providers/Microsoft.ContainerService/managedClusters/${{ parameters.cluster_name }}
                title: AKS Console
                icon: cloud
          spec:
            type: service
            lifecycle: ${{ parameters.environment }}
            owner: platform-engineering
            system: security-platform
            providesApis:
              - fixops-decision-api
              - fixops-cicd-api

    - id: publish
      name: Publish to Git Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=DevOpsMadDog&repo=fixops-azure-${{ parameters.deployment_name }}
        description: FixOps Azure deployment for ${{ parameters.environment }}
        visibility: private
        defaultBranch: main

    - id: register
      name: Register in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Terraform Configuration
        url: ${{ steps.publish.output.remoteUrl }}/tree/main/terraform
      - title: Deployment Script
        url: ${{ steps.publish.output.remoteUrl }}/blob/main/deploy.sh
      - title: Open in Backstage
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
