apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixops-evidence-lake
  namespace: fixops
  labels:
    app.kubernetes.io/name: fixops
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: fixops
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
