risk:
  max_risk_score:
    warn_above: 70
    fail_above: 85
sbom_quality:
  coverage_percent:
    warn_below: 80
    fail_below: 60
  license_coverage_percent:
    warn_below: 75
    fail_below: 50
repro:
  require_match: true
provenance:
  require_attestations: true
