apiVersion: v1
kind: Secret
metadata:
  name: fixops-secrets
  namespace: fixops
type: Opaque
stringData:
  # Replace the placeholder values with tenant-specific secrets before applying.
  SECRET_KEY: change-me
  EMERGENT_LLM_KEY: ""
  MONGO_URL: mongodb://fixops:change-me@mongodb:27017/fixops_production?authSource=admin
  REDIS_URL: redis://redis:6379/0
  JIRA_API_TOKEN: change-me
  CONFLUENCE_API_TOKEN: change-me
  VECTOR_DB_API_KEY: change-me
  THREAT_INTEL_API_KEY: change-me
