name: Provenance

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi
      - name: Build release artefact
        run: |
          mkdir -p artifacts
          git archive --format=tar.gz -o artifacts/fixops-${{ github.sha }}.tar.gz HEAD
      - name: Generate provenance attestation
        run: |
          mkdir -p artifacts/attestations
          cli/fixops-provenance attest \
            --artifact artifacts/fixops-${{ github.sha }}.tar.gz \
            --out artifacts/attestations/fixops-${{ github.sha }}.json \
            --builder-id "https://github.com/${{ github.repository }}/actions" \
            --source-uri "${{ github.server_url }}/${{ github.repository }}@${{ github.sha }}" \
            --build-type "https://github.com/actions/runner"
      - name: Verify provenance attestation
        run: |
          cli/fixops-provenance verify \
            --artifact artifacts/fixops-${{ github.sha }}.tar.gz \
            --attestation artifacts/attestations/fixops-${{ github.sha }}.json \
            --builder-id "https://github.com/${{ github.repository }}/actions" \
            --source-uri "${{ github.server_url }}/${{ github.repository }}@${{ github.sha }}" \
            --build-type "https://github.com/actions/runner"
      - name: Upload provenance attestation
        uses: actions/upload-artifact@v4
        with:
          name: provenance-attestations
          path: artifacts/attestations/
          if-no-files-found: error
